### ISSUE TITLE
"Pause in secure apps" - still can't touch the app!

### ISSUE THREAD

**Issue by leoauri** [LibreShift/red-moon#139] opened 2017-04-19 12:04 UTC
I have this new since 2.10.2

Often, the filter is deactivated as expected in secure app (owncloud, install app), but the app still doesn't respond to touch.  Quite tricky to gain access to the app at all then!

I think it happened once after timer deactivation of the filter too, but I'm not completely sure how that went.

**Comment by smichel17** [comment] 2017-04-19 14:43
Could you try a build from master? If you can't build yourself, there's a couple debug builds (albeit not quite the latest) at http://smichel.me/files/red-moon/

Reason being, I refactored the code for turning the filter on and off to hopefully make this kind of error less common. Curious if I already caught this.

**Comment by leoauri** [comment] 2017-04-21 14:38
OK, I've got 3.0.0-DEBUG running, I'll see how it goes...

**Comment by smichel17** [comment] 2017-04-22 18:57
👍 👎 ?

**Comment by leoauri** [comment] 2017-04-25 11:53
It still happened.  
I do have a hunch that it may have to do with #137, as the problem seems to occur when I have loaded more various apps during the night.  
On my phone, if I load an app, switch to another, and switch back, it's in the same state;  but if I load an app, switch to a lot of others and switch back some time later, the state is sometimes "forgotten" and the app reinitialised.  I'm not sure but I think it may be related.

**Comment by smichel17** [comment] 2017-04-25 17:35
What do you mean by "reinitialized"?

**Comment by smichel17** [comment] 2017-05-04 23:30
@leoauri Latest commit cleaned up this section of the code and may fix this. Or if it doesn't, it'll make debugging much easier :) Let me know if you get a chance to try it out. Related: #146

**Comment by smichel17** [comment] 2017-09-02 20:11
@leoauri I believe this issue had the same root cause as #142, which is fixed as of v3.1.0. When it shows up on F-Droid/GPlay (within the next few days. or you can build locally now), can you test to see if this bug remains?

**Comment by leoauri** [comment] 2017-09-03 10:18
@smichel17 I will do so, thank you...

**Comment by leoauri** [comment] 2017-09-07 07:39
Unfortunately 3.1.0 crashes upon trying to open the user interface...

**Comment by smichel17** [comment] 2017-09-07 11:33
It's actually on trying to restore the default profiles, which happens when upgrading or on first install. Fixed in master and v3.1.1, whenever F-Droid decides to update

**Comment by smichel17** [comment] 2017-09-28 21:57
v3.2.0 is released and should work. Let me know :)

**Comment by leoauri** [comment] 2017-09-29 09:50
I have to admit I don't spend as much time in secure apps as I did (migrated to Nextcloud app), but so far this seems to be working perfectly.

**Comment by smichel17** [comment] 2017-09-29 11:22
Great :)

I'm not sure exactly whre the bug was, but it had to have been some time where we set the filter to be perfectly transparent, yet didn't actually remove it from the screen. Fixed by making it so those weren't separate actions -- now there's just one `setColor()` function, which checks if that color is transparent and removes the view from the screen if so.

**Closed** 2017-09-29 11:23 UTC
Labels: bug
