### ISSUE TITLE
Cover more places with the blue light filter & dim or change colors for certain bright areas separately

### ISSUE THREAD

**Issue by 9mido** [LibreShift/red-moon#283] opened 2021-02-03 16:29 UTC
The following symbols/numbers/places are not powerful enough or do not have a blue light filter at all:

1. Battery (blue light filter not powerful enough)
2. Time (blue light filter not powerful enough)
3. Network/wifi (blue light filter not powerful enough)
4. Other notification symbols (blue light filter not powerful enough)
5. Back/forward/menu bottom buttons (blue light filter not powerful enough)
6. Lock screen (non-existent blue light filter)
7. Expansion/opening of the notification bar (non-existent blue light filter)
8. Opening some apps like the settings app (non-existent blue light filter)
9. Installing a new app and getting a popup to install (non-existent blue light filter)
10. Using the keyboard then clicking the home menu button while the keyboard is being used temporarily turns off the blue light filter then turns back on when back on the home screen. It is a quick flash of turning on/off. Or the opposite opening an app that opens the keyboard by default. 
11. Small round pill-shaped popup messages like "unable to open this link" bypass the blue light filter
12. Open with popup. (non-existent blue light filter)
13. Allow permissions for an app popup. (non-existent blue light filter)

For the not powerful enough ones, there needs to be a way to dim these white symbols or change the color of them separately. The blue light filter covers them but the white still shows significantly more than the blue light filter in dark environments.

**Comment by smichel17** [comment] 2021-02-04 03:53
This is probably a duplicate of one of the other issues on newer versions of Android, [label: `apiv26+`](https://github.com/LibreShift/red-moon/issues?q=is%3Aissue+is%3Aopen+label%3Aapi26%2B).

**Comment by 9mido** [comment] 2021-02-04 15:58
I thought it was a bit different then the other issues because although the blue light filter covers the entire screen, some parts are appearing as though they are above the blue light filter and bypass it. In other places like the lock screen, expanded notification bar, and opening some apps the blue light filter is non-existent. It would be nice to have an entirely blue light filter experience throughout the entire android phone.

**Comment by smichel17** [comment] 2021-05-23 00:48
I will close this. Certain parts of the screen not being filtered is covered by other issues. Detecting what's on the screen and dimming it more if needed is beyond the scope of Red Moon. Pausing in apps that are secured against overlays is by design and can already be modified per-screen or disabled/enabled entirely (the "Pause in excluded apps" setting); root mode (#150) would allow not excluding those apps.

**Closed by smichel17** 2021-05-23 00:48 UTC
Labels: enhancement
