### ISSUE TITLE
System nav bar is not dimmed

### ISSUE THREAD

**Issue by codingWhatzThat** [LibreShift/red-moon#245] opened 2019-03-02 04:52 UTC
What are the use of a blazing triangle, circle, and square when I'm trying to read comfortably in the dark?  The option exists to also dim the android soft buttons in the control bar.  Could that not also be an option in the app's settings?  When my pupils are fully dilated to see in the dark, it's a bit of a nuisance to have these control icons glowing so intensely in relation to everything else in my field of view.  Can the option to dim them also be added to the app?

**Comment by codingWhatzThat** [comment] 2019-03-02 05:00
I see now this is already mentioned in the issue preceding...

**Comment by codingWhatzThat** [comment] 2019-03-02 05:21
PLEASE GIVE OPTION TO DIM FULL SCREEN!!

These bright shapes do prove to be a bit of a nuisance. I'd be happy to see dimming them as a settings option. By now, I've got geometric retina burn from trying to see past these three blazing control icons all the time.

I use several apps that cover the nav bar on my Moto E4.  With Red Moon, though, the nav bar is never dimmed so far.  To a point, it defeats the purpose *not* to allow the full screen to be dimmed!  Please someone fix this?

**Comment by smichel17** [comment] 2019-03-02 08:10
What Android version are you using?

**Comment by codingWhatzThat** [comment] 2019-03-02 17:30
Nougat 7.1.1

**Comment by Slion** [comment] 2020-02-18 06:31
Same issue on android 9.

**Comment by smichel17** [comment] 2020-03-03 12:20
Closing as a duplicate of #252, which has screenshots.

**Closed by smichel17** 2020-03-03 12:20 UTC
