### ISSUE TITLE
Make it more TV friendly?

### ISSUE THREAD

**Issue by HiddenLeveI** [LibreShift/red-moon#337] opened 2023-07-18 04:51 UTC
Hello, I have an Android TV and wanted a night mode so I downloaded this app on there. But it needs special permissions that my TV can't give it. Any workarounds or ideas?

**Comment by NoahAndrews** [comment] 2023-07-18 23:34
Duplicate of https://github.com/LibreShift/red-moon/issues/227

**Comment by HiddenLeveI** [comment] 2023-07-19 01:52
#282 doesn't apply to me. My issue is that it needs the permission to appear over other apps or something like that yet it doesn't pop up for me to switch it on the TV.

**Closed** 2024-02-07 17:18 UTC
