### ISSUE TITLE
Temperature not remembered with Timer on.

### ISSUE THREAD

**Issue by joeyjbeckman** [LibreShift/red-moon#133] opened 2017-03-26 07:33 UTC
Using Red Moon on Marshmallow, I have saved a custom filter with a temperature ~2800K, but at sunset when it automatically turns on, it reddens the screen to ~800K.

**Comment by smichel17** [comment] 2017-03-26 07:56
Which version are you on? Does this occur if you change the saved filter or only when the filter is on custom?

Version 3.0, when it is released, has a lot of backend changes to profiles and it's likely that this bug does not exist on it (not because I specifically fixed it, but because of how many changes there were).

**Comment by joeyjbeckman** [comment] 2017-03-26 15:40
I am on version 2.10.1. And yes it also occurs if I change the saved filter.

Turning the filter on and then off has no effect, but changing to a different filter and then back to my filter corrects the temperature. Any idea when version 3.0 will be released?

**Comment by smichel17** [comment] 2017-03-27 03:22
Basically once @raatmarien has the chance to look them over and make sure they are changes she wants to release.

**Comment by smichel17** [comment] 2017-04-02 08:51
@joeyjbeckman If you want to try this earlier to confirm whether the bug is fixed, you can get a debug version [here](http://smichel.me/files/red-moon/red-moon-debug-2017-04-02.apk) (from aa9c553, if you'd prefer to build yourself). The debug build will install alongside the version from fdroid/gplay.

**Comment by joeyjbeckman** [comment] 2017-04-13 14:22
I tried the debug version, but unfortunately it seems like the bug has not been fixed.

**Comment by smichel17** [comment] 2017-04-13 16:26
> Turning the filter on and then off has no effect, but changing to a different filter and then back to my filter corrects the temperature.

Does it correct the temperature the next time Red Moon turns on using the timer, too, or only when you do it manually?

Can you reproduce this issue for intensity or dim level, too?

If you could share a specific order of steps to take in order to trigger the bug, that would be helpful, too.

**Comment by smichel17** [comment] 2020-03-18 21:53
Closing because I don't have enough info to reproduce this. If you (or anyone) can still reproduce this on the latest version of Red Moon, please open a new bug report :heart:

**Closed by smichel17** 2020-03-18 21:53 UTC
Labels: bug, needsinfo
