### ISSUE TITLE
Turn off when screenshotting

### ISSUE THREAD

**Issue by rileyball** [LibreShift/red-moon#255] opened 2019-08-15 03:23 UTC
The app should not capture the redness when screenshotting. It's so annoying whenever I screenshot and the picture looks super red to whoever I send it too.

**Comment by smichel17** [comment] 2019-08-15 05:03
Duplicate of #104.

I agree it *should* work this way in theory, but it's difficult to impossible to implement.

**Closed** 2019-08-15 05:03 UTC
