### ISSUE TITLE
Create better filter driver with root support 

### ISSUE THREAD

**Issue by MikolajQ** [LibreShift/red-moon#273] opened 2020-03-21 00:09 UTC
Would be great to see better blue light filter. There is cf.lumen app, and it has amazing original CF.lumen driver - the KCAL kernel driver, and it's simply perfect filter with no fog, only blue light filter as it should be. Any other app in the world has no such a great filter. Unfortunately cf.lumen is no longer supported and doesn't work with newer Android versions. This feature will make this app the best of the best.

**Comment by smichel17** [comment] 2020-03-21 00:51
Duplicate of #150.

**Closed by smichel17** 2020-03-21 00:51 UTC
Labels: enhancement

**Comment by smichel17** [comment] 2020-03-21 00:53
I agree a root mode filter is the best. I'd love to implement it; it's just a matter of how much time I have to spend on Red Moon and other priorities (I want to do #114 first).

**Comment by smichel17** [comment] 2020-03-21 00:55
Duplicate of #150
