### ISSUE TITLE
Red moon doesn't auto turn on in Redm8 Note 3

### ISSUE THREAD

**Issue by Sibasish** [LibreShift/red-moon#258] opened 2019-09-06 13:26 UTC
Hey,
  I have been using this all for quite some time and it is a great relief since I have been using this app, especially at night.
 However, recently this app isn't turning on at the sunrise time inspite of the location being set. But it auto turns off on its own.
Please suggest what can be done about it.
Red Moon version - 3.4.0
Android version - Android Marshmallow, and device model - Redmi Note 3

**Comment by Sibasish** [comment] 2019-09-10 12:50
Please respond on the issue detailed here.

**Comment by Sibasish** [comment] 2019-10-12 05:33
Can anyone please look into this issue?

**Comment by smichel17** [comment] 2020-03-04 18:28
Red Moon is known to have issues on the Redmi Note 3. Closing as a duplicate of #213 .

**Closed by smichel17** 2020-03-04 18:28 UTC
Labels: bug

**Comment by smichel17** [comment] 2020-03-04 18:33
Copying from that issue:

> Can you find a way to make Red Moon exempt from battery optimization features and see if this fixes the problem? How to do this is a little different on each device, but here is an example of how to do it on some devices.
> 
> https://fieldguide.gizmodo.com/how-to-exclude-certain-apps-from-androids-battery-savin-1742064352
